language: python
python:
  - "3.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install tox-travis coverage
# command to run tests, e.g. python setup.py test
script:  tox

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks: https://discordapp.com/api/webhooks/269325473312407552/CDWAn_COXdkt3sDsDN2z0acLjhRDObovBNOXzl0vJaASeEgvYyGoddpZD_P5iacmivto